// ================================================================
//  config.js — ÚNICA FUENTE DE VERDAD
// ================================================================
const CONFIG = {

  SUPABASE_URL: 'https://hicrocsgqcfwilpuhqoo.supabase.co',
  SUPABASE_KEY: 'sb_publishable_2ppgnZ9CetTDMOY1g3XgFA_B8Ggb_l7',

  W: 800,
  H: 450,

  GRAVITY:      900,
  JUMP_VY:     -520,

  SPD_NORMAL:   230,
  SPD_FAST:     380,
  SPD_SLOW:      90,
  FAST_MS:     3000,
  SHAKE_G:       14,

  GLUCOSE_INIT:    100,
  GLUCOSE_MIN:      20,
  GLUCOSE_MAX:     400,
  RANGE_LO:         80,
  RANGE_HI:        130,
  RANGAZO_LO:       90,
  RANGAZO_HI:      110,
  HYPO_THRESH:      50,
  HYPER_THRESH:    180,

  DROP_RUN:        2.0,
  DROP_FAST:       4.0,
  DROP_JUMP:       2.0,
  DROP_SLOPE:      2.5,

  // Insulina lenta: 5 mg/dL/s durante 5s por dosis — acumulable
  INS_SLOW_DPS:    6,
  INS_SLOW_MS:  5000,
  INS_FAST_DROP:  80,
  INS_FAST_MAX:    4,
  INS_FAST_PICKUP: 1,   // dosis que da cada pickup de insulina rápida
  INS_FAST_RECHARGE_MAX: 3, // máximo al recargar

  ENEMY_RAISE: {
    lollipop:  30,
    cake:     200,
    choco:     70,
  },
  CUPCAKE_SLOW_MS: 2000,

  // Manzanas: se guardan en mochila y se comen bajo demanda
  APPLE_RAISE:    40,
  BACKPACK_START:  3,
  BACKPACK_MAX:    6,

  GLUCAGON_MAX:  2,
  GLUCAGON_VAL: 80,

  PTS_RANGAZO:   100,
  PTS_IN_RANGE:   60,
  PTS_OUT:        10,
  SPEED_BONUS:   500,
  SPEED_REF_S:    90,

  GROUND_Y:      390,
  GROUND_H:       60,

  LEVELS: [
    {
      id: 1, name: 'Bosque',
      skyColor:    0x2E7D32,
      groundColor: 0x4E342E,
      groundEdge:  0x7CB342,
      enemyTypes:  ['lollipop'],
      enemySpd:    60,
      density:     0.20,
      checkpoints: 4,
      apples:      3,
      glucagons:   2,
      length:      7000,
      holePct:     0.04,
      slopePct:    0.00,
      slopeRise:   0,
    },
    {
      id: 2, name: 'Montaña',
      skyColor:    0x78909C,
      groundColor: 0x455A64,
      groundEdge:  0xB0BEC5,
      enemyTypes:  ['lollipop', 'cake'],
      enemySpd:    80,
      density:     0.35,
      checkpoints: 5,
      apples:      3,
      glucagons:   2,
      length:      8000,
      holePct:     0.06,
      slopePct:    0.15,
      slopeRise:   40,
    },
    {
      id: 3, name: 'Ciudad',
      skyColor:    0x0D0D2B,
      groundColor: 0x1A237E,
      groundEdge:  0x3949AB,
      enemyTypes:  ['lollipop', 'cake', 'choco'],
      enemySpd:    100,
      density:     0.50,
      checkpoints: 5,
      apples:      2,
      glucagons:   2,
      length:      8500,
      holePct:     0.08,
      slopePct:    0.22,
      slopeRise:   60,
    },
    {
      id: 4, name: 'Laboratorio',
      skyColor:    0x0A1628,
      groundColor: 0x0D2040,
      groundEdge:  0x00FF88,
      enemyTypes:  ['lollipop', 'cake', 'choco'],
      enemySpd:    120,
      density:     0.65,
      checkpoints: 6,
      apples:      2,
      glucagons:   1,
      length:      9000,
      holePct:     0.10,
      slopePct:    0.28,
      slopeRise:   80,
    },
    {
      id: 5, name: 'País del Dulce',
      skyColor:    0xF48FB1,
      groundColor: 0xAD1457,
      groundEdge:  0xFF80AB,
      enemyTypes:  ['lollipop', 'cake', 'choco'],
      enemySpd:    140,
      density:     0.80,
      checkpoints: 6,
      apples:      1,
      glucagons:   1,
      length:      10000,
      holePct:     0.12,
      slopePct:    0.35,
      slopeRise:   100,
    },
  ],
};
